local NotificationLibrary = loadstring(game:HttpGet('https://raw.githubusercontent.com/thuarnel/rbx-ui-libs/refs/heads/main/Notifications/Lo/main.lua'))()
NotificationLibrary:SendNotification("Success", "I'm a cool message", 3)
NotificationLibrary:SendNotification("Warning", "I'm a cool message", 3)
NotificationLibrary:SendNotification("Error", "I'm a cool message", 3)
NotificationLibrary:SendNotification("Info", "I'm a cool message", 3)
